### ISSUE TITLE
I have error "Error: error:unpr Unknown Provide"

### ISSUE THREAD

**Issue by artem-galas** [iominh/ng-scrollbars#4]
Hi, I connect the directive analogue to how it's described in your Readme, but I get [Angular Error](https://docs.angularjs.org/error/$injector/unpr?p0=aProvider%20%3C-%20a%20%3C-%20ngScrollbarsDirective) .
What am I doing wrong?

Thanks.

**Comment by iominh** [comment]
Hi Artem, thanks for the issue.

Unfortunately, I haven't encountered that issue yet. Are there no other errors? Are you sure you injected the ngScrollbars module in your app (e.g. var app = angular.module('app', ['ngScrollbars']))?

I just created a new demo and made it very simple, maybe you could see if this particular version works for you: http://minhongrails.github.io/ng-scrollbars/demo1.html (just view the source directly or go to https://github.com/minhongrails/ng-scrollbars/tree/gh-pages to see the github code on the branch).

Otherwise, the normal demo is available at http://minhongrails.github.io/ng-scrollbars/

Any other info you could provide would help a lot because I'm not sure how to reproduce your issue

**Comment by iominh** [comment]
Unable to reproduce. Please re-open if you still have this issue and can provide more details
