### ISSUE TITLE
¿Can I put setHeight in the html?

### ISSUE THREAD

**Issue by brujo-rojas** [iominh/ng-scrollbars#8]
Example:

``` html
<div ng-scrollbars ng-scrollbars-config="config" ng-scrollbars-height="dinamicHeight">

</div>
```

because I have a lot of scrolls and I need diferents heights

**Comment by iominh** [comment]
Currently right now you can't. I could add this feature but the question is how many configurations should be possible through the html because there's a lot of configuration options. Also I don't know of the performance impact. However, I'll look into it at some point.

So for now, if you have a lot of scrollbars that need different heights, I would create a separate ng-scrollbars-config for each. For example:

``` js
$scope.sb1Config = {
    autoHideScrollbar: false,
    theme: 'light',
    advanced:{
        updateOnContentResize: true
    },
        setHeight: 600,
        scrollInertia: 0
    }
}

$scope.sb2Config = {
    autoHideScrollbar: false,
    theme: 'light',
    advanced:{
        updateOnContentResize: true
    },
        setHeight: 500,
        scrollInertia: 0
    }
}
```

``` html
<div ng-scrollbars ng-scrollbars-config="sb1Config">
</div>

<div ng-scrollbars ng-scrollbars-config="sb2Config">
</div>
```

**Comment by brujo-rojas** [comment]
I change the height with CSS diretly, with a !important

**Comment by iominh** [comment]
I'm glad you were able to resolve the issue. sorry for the year long response haha, I meant to reply earlier. If you encounter any other issues let me know and I'll re-open

**Comment by jmls** [comment]
@brujo696 : could you explain how you made this work ? thanks
