### ISSUE TITLE
Undefined is not a function on the directive link method 

### ISSUE THREAD

**Issue by sam2x** [iominh/ng-scrollbars#9]
Hi, 

First, thanks for your package. I encountered a weirdz bug, i'm not sure how to solve it. 

I correctly loaded the resources in my index.html 

```
<link rel="stylesheet" href="./bower_components/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css" type="text/css"/>
[...]
<script src="./bower_components/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>
<script src="./bower_components/ng-scrollbars/src/scrollbars.js"></script>
```

Then i load the dependence inside my app.js. I use the default configuration inside the provider (the one provided by the readme) : 

```
.config(function (ScrollBarsProvider) {
    ScrollBarsProvider.defaults = {
        scrollButtons: {
            scrollAmount: 'auto', // scroll amount when button pressed
            enable: true // enable scrolling buttons by default
        },
        scrollInertia: 400, // adjust however you want
        axis: 'yx', // enable 2 axis scrollbars by default
        theme: 'dark',
        autoHideScrollbar: true
    };
})
```

Next, I have the element call within a dynamic menu builder : 
    `<div ng-scrollbars></div>`

When it is rendered, i get : 

```
TypeError: undefined is not a function
at ScrollBarsDirective.link (http://192.168.0.14:8000/bower_components/ng-scrollbars/src/scrollbars.js:69:14)
at http://192.168.0.14:8000/js/app.min.js:2:4695
at oe (http://192.168.0.14:8000/js/app.min.js:2:4752)
at w (http://192.168.0.14:8000/js/app.min.js:1:31242)
at a (http://192.168.0.14:8000/js/app.min.js:1:27065)
at w (http://192.168.0.14:8000/js/app.min.js:1:31191)
at a (http://192.168.0.14:8000/js/app.min.js:1:27065)
at w (http://192.168.0.14:8000/js/app.min.js:1:31191)
at http://192.168.0.14:8000/js/app.min.js:2:2467
at c (http://192.168.0.14:8000/js/app.min.js:2:27186) <div ng-scrollbars="" class="ng-isolate-scope">
```

The error comes from a function call inside the link method  : 
    elem.mCustomScrollbar(config);

From my perspective, it means that mCustomScrollbar isnt declared/defined inside elem context. I don't understand why.... 
Any ideas about what could be the problem ?  Anyone encountered this ? 

Thanks!

**Comment by iominh** [comment]
Hmm, it looks like mCustomScrollbar isn't defined for some reason (either the scrollbar elem or mCustomScrollbar is null). Are there any other errors on the page and did the page include jquery.mCustomScrollbar.concat.min.js correctly? Are you using ng-scrollbars within another directive? Overall, if we could somehow reproduce the scenario you're running it in it would help to debug the issue since I haven't seen it yet.

I created a basic demo (http://minhongrails.github.io/ng-scrollbars/demo3.html) to replicate your situation but it appears to work so please take a look at it to see if there's anything missing. For example, did you inject ngScrollbars for your app?

``` javascript
var app = angular.module('app', ['ngScrollbars']);
```

**Comment by sam2x** [comment]
I have included all ressources and the dependence correctly.  Yes it is included inside another directive, is this bad ? I'm investigating your demo and my code.

**Comment by iominh** [comment]
Including it inside another directive should be fine but another user had issues so overall it just depends how you're using it inside the other directive. In general, if we can somehow replicate your scenario in a test case (maybe like a modified version of demo3.html) then I can see the problem and try to fix it

**Comment by sam2x** [comment]
Here some information about the context (sorry the project starting to be big, it's not easy to make a test case) : 
- The ng-scrollbars directive is located in a html file
- The html file is loaded from a module which contains a directive i use.
- The html file is loaded by this module via the  'templateUrl'.
- The module that's using the directive is then loaded as a dependence inside my main application.

I think i made a mistake about 'which module' need to load the dependency. I'm trying to see if it works to load it inside the directive module.

**Comment by iominh** [comment]
Ah okay, well, I'll probably try to create some test scenarios for ng-scrollbars within other directives at some point, but it may just be guesswork until I can see the errors you're encountering. However, I do appreciate all the info you've provided!

The quick solution is you may not even need ng-scrollbars. You might be able to just call the following from within your directive:

``` javascript
elem.mCustomScrollbar(config);
// you can use the config object that I have in the examples or go to http://manos.malihu.gr/jquery-custom-content-scroller/ to read more info
```

That was the solution we had for the other ng-scrollbars user who had issues using it within another directive. Basically the problem was that his directive was adding/compiling/linking ng-scrollbars too late where his ng-scrollbars was applied before his directive had any content, so it wasn't showing the scrollbars since mCustomScrollBar saw an empty div. He didn't get an error like you do, however. Instead he just didn't see any scrollbars.

**Comment by sam2x** [comment]
Issue solved, the problem was the order of js inclusion inside my index.html. Creating a fresh project with _yo_, and added some module, I had something like : 

```
<script src="js/app.min.js"></script>
<script src="./bower_components/lodash/dist/lodash.min.js"></script>
<script src="./bower_components/XXXX.js"></script>
<script src="./bower_components/YYYY.js"></script>
<script src="./bower_components/ZZZZ/restangular.js"></script>
```

It was important for some module to not be included before the app.min.js. So i decided to add all other libs after this app.min.js. Even jquery, which was absolutely not a problem with other jquery-module. In fact i never got problems like this. Now i guess since my directive was inside a directive, this directive was loaded first (via app.min.js), then the "compiler" found the directive of jquery module (which were not loaded yet), it triggered my error. 

So my solution, add 'only' jquery and the required jquery module before your angular app.min.js, like this : 

```
<script src="./bower_components/jquery/dist/jquery.min.js"></script>
<script src="./bower_components/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.js"></script>    
<script src="js/app.min.js"></script>
```

What a waste of time, thanks you for your analyze, hope my response will help others ;).
S.

**Comment by iominh** [comment]
Yay! I'm glad you got it working :), and thanks so much for the detail, I'm sure it will help anyone else who encounters similar issues. If it wouldn't be too much trouble, would you mind staring this repo? That'll really help me, since more people will use the project so it'll be tested more and be better overall.

Thanks!
